### PR TITLE
fixes #51  white flash bug

### LINKED ISSUE #51: White flash with certain characters
Some characters have some problems where a white flash is shown from time to time (when animation loop ends)

Specially Klavier and Apollo

@RobiMez is taking a look on it

### PR DESCRIPTION
**Pull request by RobiMez**
fixes #51
adds modified assets
huge thanks to @finthecat
he did most ( all of the work on the assets ) of the work

adds a couple of missing emotions in constants 
adds testing scripts for the assets

### CODE REVIEW

**Comment by RobiMez** [comment]
Replacements for the faulty assets : 
[Sprites-Apollo.zip](https://github.com/LuisMayo/objection_engine/files/7369018/Sprites-Apollo.zip)
[Sprites-Klavier.zip](https://github.com/LuisMayo/objection_engine/files/7369025/Sprites-Klavier.zip)
[Sprites-mia.zip](https://github.com/LuisMayo/objection_engine/files/7369029/Sprites-mia.zip)

**Comment by FinTheCat** [comment]
I threw the gifs into Aseprite, changed their color profiles to RGB, then exported them:
sprite > color mode > rgb
file > export > (enter, enter)
file > close
(repeat for all the files)

The shadow frame bug caused by the error (explained [here](https://community.aseprite.org/t/animated-gif-export-rounding-frame-durations/1181)) was fixed by throwing the gifs into Photoshop, and exporting them (with the default settings) to fix the shadowing:
File > Export > Save for Web (Legacy)

My assumption is that I just could have thrown them into Photoshop, have the color profile automatically be changed to RGB / sRGB, then export it.

**Comment by RobiMez** [comment]
Codewise the bug was originating in the pillow code to convert to RGBA mode found in the constructor of AnimImg in beans>img.py where it was possibly using a faulty palette. also confirmed by @FinTheCat

**Comment by RobiMez** [comment]
fixed that with 105c06f

**Pull request merged**
