### PR TITLE
fixes #36

### LINKED ISSUE #36: Include other characters
- [ ] Apollo Justice

### PR DESCRIPTION
**Pull request by RobiMez**
zip file of sprites attached

[REMOVED]

### CODE REVIEW

**Comment by wanghaisheng** [comment]
@RobiMez where is the assets for new added characters

**Comment by RobiMez** [comment]
@wanghaisheng 
image

You can find them in the logs ... its been a while so i cant find them on my local machine.

**Comment by wanghaisheng** [comment]
response = requests.get('https://dl.luismayo.com/assets.zip')

**Comment by LuisMayo** [comment]
Downloading from that URL will get you the assets. Yup

**Comment by wanghaisheng** [comment]
@LuisMayo  can u just look at my old tts question.
i can generate tts sound file from text but the issue is how to concat this with your background and replace typewritting sound,core issue is the frame time length need to be consistent

**Pull request merged**
