### PR TITLE
New music support

### PR DESCRIPTION
**Pull request by jonatep**
A new argument has been given to the function "comments_to_scene", name_music. Depending of the value of this string, the music should change when rendering the video. The possible values of name_music are:

PWR: Just like the default bot, using music from the first game
JFA: Music from Justice for All
TAT: Music from Trials and Tribulations

The new music tracks are in this folder: https://drive.google.com/drive/folders/1CSMvRfn8awGaZV_6Lra0hseYo4LsbP85?usp=sharing 
The music files' names are the same ones as in the code.
I'm sure this isn't perfect, so please tell me any mistakes I may have made :)

### CODE REVIEW

**Review by LuisMayo — CHANGES_REQUESTED** [review]
Hi!
Really nice PR!

It looks really good
I will need a few changes if you'd be so kind as of doing it.

- [ ] Could you make game_music optional and default it to 'PWR'. It should be as easy as writting `name_music="PWR"`
- [ ] The code currently don't run. You can try yourself by executing `python example.py`. This is due to the fact that name_music is specified after **kwargs. Move it so **kwargs is always the last item of the function header.

That being said it looks good!
Thanks a lot for your help, it means a lot.

P.S: If you could send me the files via DM or any other way of communication I'd be most gratefully

**Comment by LuisMayo** [comment]
Forget the last bit, I didn't see you had already provided the files.
Thanks

**Comment by jonatep** [comment]
I think the pull request has been updated correctly. Thanks for thee feedback!

**Review by LuisMayo — CHANGES_REQUESTED** [review]
Hi!
Thanks for the changes,

However I've found another bug.
When an "objection!" is raised the "objection" music is re-starting. I'm pretty sure it is due to the `change_audio=True` line. It seems it's out of all the ifs, while it should be in.

As always, You can run `python example.py` to do some sort of manual testing.

Thanks a lot for your work

**Comment by jonatep** [comment]
After some proper testing using my own Twitter API, I think that with the changes here and in my other pr (https://github.com/LuisMayo/ace-attorney-twitter-bot/pull/20) the music implementation should work with no major issues! Thanks again for the feedback!

**Comment by LuisMayo** [comment]
Currently I don't have access to a computer and I won't have probably until Sunday but it looks promising!

I'll get to it ASAP.

Thanks a lot for your work!

**Comment by LuisMayo** [comment]
Currently I don't have access to a computer and I won't have probably until Sunday but it looks promising!

I'll get to it ASAP.

Thanks a lot for your work!

**Review by LuisMayo — APPROVED** [review]

**Comment by LuisMayo** [comment]
It's merged now!

**Pull request merged**
